# templates/cax-eqc2.sparql
# cax-eqc2
# T(?c1, owl:equivalentClass, ?c2)
# T(?x, rdf:type, ?c2)
#=======
# T(?x, rdf:type, ?c1)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?x AS ?ts) (rdf:type AS ?tp) (?c1 AS ?to)
WHERE {
	 ?c1 owl:equivalentClass ?c2 .
	 ?x rdf:type ?c2 .

	 ?x rdf:type ?c1 .
	 FILTER(?c1!=?c2)
}
