# templates/cls-nothing1.sparql
# cls-nothing1
# 
#=======
# T(owl:Nothing, rdf:type, owl:Class)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select (owl:Nothing as ?ts) (rdf:type as ?tp) (owl:Class as ?to)
where
{}