# templates/cls-oo-1.sparql
# cls-oo
# T(?c, owl:oneOf, ?x)
# LIST[?x, ?y1, ..., ?yn]
#=======
# T(?y1, rdf:type, ?c)
# ...
# T(?yn, rdf:type, ?c)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?yn (rdf:type as ?tp) ?c
where
{
    ?c owl:oneOf/rdf:frist/rdf:rest* ?yn .

    ?yn rdf:type ?c .
}