# templates/dt-type2.sparql
# dt-type2
# 
# =======
# T(lt, rdf:type, dt)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?lt (rdf:type as ?tp) ?dt
where
{
?lt a ?dt.
filter(isLiteral(?lt))
}