# templates/eq-rep-o.sparql
# eq-rep-o
# T(?o, owl:sameAs, ?o')
# T(?s, ?p, ?o)
# =======
# T(?s, ?p, ?o')
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?s AS ?ts) (?p AS ?tp) (?o_prim AS ?to)
WHERE {
	 ?o owl:sameAs ?o_prim .
	 ?s ?p ?o .

	 ?s ?p ?o_prim .

	 filter(?o!=?o_prim)
}
