# templates/eq-ref-2.sparql
# eq-ref
# T(?s, ?p, ?o)
# =======
# T(?s, owl:sameAs, ?s)
# T(?p, owl:sameAs, ?p)
# T(?o, owl:sameAs, ?o)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?p AS ?ts) (owl:sameAs AS ?tp) (?p AS ?to)
WHERE {
	 ?s ?p ?o .

	 ?p owl:sameAs ?p .

	 filter(?p!=owl:sameAs)
}
