# templates/eq-sym.sparql
# eq-sym
# T(?x, owl:sameAs, ?y)
# =======
# T(?y, owl:sameAs, ?x)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?y AS ?ts) (owl:sameAs AS ?tp) (?x AS ?to)
WHERE {
	 ?x owl:sameAs ?y .

	 ?y owl:sameAs ?x .

	 filter(?x!=?y)
}
