# templates/eq-trans.sparql
# eq-trans
# T(?x, owl:sameAs, ?y)
# T(?y, owl:sameAs, ?z)
# =======
# T(?x, owl:sameAs, ?z)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?x AS ?ts) (owl:sameAs AS ?tp) (?z AS ?to)
WHERE {
	 ?x owl:sameAs ?y .
	 ?y owl:sameAs ?z .

	 ?x owl:sameAs ?z .

	 filter(?x!=?y && ?y!=?z && ?x!=?z)
}
