# templates/prp-ifp.sparql
# prp-ifp
# T(?p, rdf:type, owl:InverseFunctionalProperty)
# T(?x1, ?p, ?y)
# T(?x2, ?p, ?y)
# =======
# T(?x1, owl:sameAs, ?x2)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?x1 AS ?ts) (owl:sameAs AS ?tp) (?x2 AS ?to)
WHERE {
	 ?p rdf:type owl:InverseFunctionalProperty .
	 ?x1 ?p ?y .
	 ?x2 ?p ?y .

	 ?x1 owl:sameAs ?x2 .
	 filter(?x1!=?x2)
}
