# templates/prp-trp.sparql
# prp-trp
# T(?p, rdf:type, owl:TransitiveProperty)
# T(?x, ?p, ?y)
# T(?y, ?p, ?z)
# =======
# T(?x, ?p, ?z)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?x AS ?ts) (?p AS ?tp) (?z AS ?to)
WHERE {
	 ?p rdf:type owl:TransitiveProperty .
	 ?x ?p ?y .
	 ?y ?p ?z .

	 ?x ?p ?z .
	 filter(?x!=?y && ?y!=?z && ?x!=?z)
}
