# templates/prp-symp.sparql
# prp-symp
# T(?p, rdf:type, owl:SymmetricProperty)
# T(?x, ?p, ?y)
# =======
# T(?y, ?p, ?x)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?y AS ?ts) (?p AS ?tp) (?x AS ?to)
WHERE {
	 ?p rdf:type owl:SymmetricProperty .
	 ?x ?p ?y .

	 ?y ?p ?x .
	 filter(?x!=?y)
}
