# templates/prp-inv2.sparql
# prp-inv2
# T(?p1, owl:inverseOf, ?p2)
# T(?x, ?p2, ?y)
# =======
# T(?y, ?p1, ?x)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?y AS ?ts) (?p1 AS ?tp) (?x AS ?to)
WHERE {
	 ?p1 owl:inverseOf ?p2 .
	 ?x ?p2 ?y .

	 ?y ?p1 ?x .
	 filter(?x!=?y)
}
