# templates/scm-dom2.sparql
# scm-dom2
# T(?p2, rdfs:domain, ?c)
# T(?p1, rdfs:subPropertyOf, ?p2)
# =======
# T(?p1, rdfs:domain, ?c)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?p1 AS ?ts) (rdfs:domain AS ?tp) (?c AS ?to)
WHERE {
	 ?p2 rdfs:domain ?c .
	 ?p1 rdfs:subPropertyOf ?p2 .

	 ?p1 rdfs:domain ?c .
	 filter(?p1!=?p2)
}
