# templates/scm-sco.sparql
# scm-sco
# T(?c1, rdfs:subClassOf, ?c2)
# T(?c2, rdfs:subClassOf, ?c3)
# =======
# T(?c1, rdfs:subClassOf, ?c3)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?c1 AS ?ts) (rdfs:subClassOf AS ?tp) (?c3 AS ?to)
WHERE {
	 ?c1 rdfs:subClassOf ?c2 .
	 ?c2 rdfs:subClassOf ?c3 .

	 ?c1 rdfs:subClassOf ?c3 .
	 filter(?c1!=?c2 && ?c2!=?c3 && ?c1!=?c3)
}
