# templates/scm-eqc1-2.sparql
# scm-eqc1
# T(?c1, owl:equivalentClass, ?c2)
# =======
# T(?c1, rdfs:subClassOf, ?c2)
# T(?c2, rdfs:subClassOf, ?c1)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?c2 AS ?ts) (rdfs:subClassOf AS ?tp) (?c1 AS ?to)
WHERE {
	 ?c1 owl:equivalentClass ?c2 .

	 ?c2 rdfs:subClassOf ?c1 .
}
