# templates/scm-cls-3.sparql
# scm-cls
# T(?c, rdf:type, owl:Class)
# =======
# T(?c, rdfs:subClassOf, ?c)
# T(?c, owl:equivalentClass, ?c)
# T(?c, rdfs:subClassOf, owl:Thing)
# T(owl:Nothing, rdfs:subClassOf, ?c)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (?c AS ?ts) (rdfs:subClassOf AS ?tp) (owl:Thing AS ?to)
WHERE {
	 ?c rdf:type owl:Class .

	 ?c rdfs:subClassOf owl:Thing .
}
